name: connection_wrapper
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com

environment:
  sdk: '>=3.1.2 <4.0.0'
  # 3.1.2 - 3.2.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
